# Generated by Django 5.2 on 2025-04-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('D', '데이'), ('E', '이브닝'), ('N', '나이트'), ('OFF', '휴무')], max_length=3)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.nurse')),
            ],
            options={
                'unique_together': {('nurse', 'date')},
            },
        ),
    ]
