# Generated by Django 5.2 on 2025-04-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('D', '데이'), ('E', '이브닝'), ('N', '나이트')], max_length=3, unique=True)),
                ('required_staff', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
