# Generated by Django 5.2 on 2025-04-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_staffingrequirement'),
    ]

    operations = [
    ]
