# Generated by Django 5.2 on 2025-04-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_shiftchangehistory'),
    ]

    operations = [
    ]
