# Generated by Django 5.2 on 2025-04-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_shiftchangehistory'),
        ('scheduler', '0006_remove_schedule_created_at_shiftchangehistory'),
    ]

    operations = [
    ]
