# Generated by Django 5.2 on 2025-04-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_merge_20250425_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurse',
            options={'verbose_name': '간호사', 'verbose_name_plural': '간호사들'},
        ),
        migrations.AddField(
            model_name='nurse',
            name='is_night_keeper',
            field=models.BooleanField(default=False, verbose_name='나이트 킵'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='skill_level',
            field=models.IntegerField(choices=[(1, '초급 1'), (2, '초급 2'), (3, '중급 1'), (4, '중급 2'), (5, '고급 1'), (6, '고급 2')], default=1, verbose_name='숙련도'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='사번'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='이름'),
        ),
    ]
